# Configuration for best performing model
defaults:
  - model: comparison_siamese_unified_best

# Task configuration
task_type: comparison

# Data configuration
data:
  targets:
    - attractive
    - smart
    - trustworthy
  embeddings_cache_file: clip_embeddings_cache.pkl
  force_recompute_embeddings: false

# Training configuration
training:
  epochs: 100
  learning_rate: 0.001
  validation_split: 0.2
  augment_swapped_pairs: true
  optimizer: adamw
  weight_decay: 0.01

# GPU configuration
gpu:
  device_id: 1

# Hydra configuration
hydra:
  run:
    dir: outputs/${now:%Y-%m-%d}/${now:%H-%M-%S}
  sweep:
    dir: multirun/${now:%Y-%m-%d}/${now:%H-%M-%S}
    subdir: ${hydra.job.num}