# Configuration for individual rating prediction
model:
  hidden_dims: [256, 128, 64]  # List of hidden layer dimensions
  activation: 'relu'  # Options: relu, tanh, leaky_relu
  dropout: 0.2  # Dropout rate (0 to disable)
  use_batch_norm: false  # Whether to use batch normalization

training:
  epochs: 50
  learning_rate: 0.001
  batch_size: 32
  validation_split: 0.2

data:
  cache_embeddings: true
  embeddings_cache_file: 'clip_embeddings_cache.pkl'

gpu:
  device_id: 1  # Which GPU to use