# Best configuration for rating task with unified model
defaults:
  - unified_base

task_type: rating

# Best hyperparameters (same architecture as comparison)
model:
  hidden_dims:
    - 512
    - 256
    - 128
  activation: gelu
  dropout: 0.3
  batch_norm: true
  layer_norm: false
  use_user_encoding: false  # Could enable for user-specific rating

training:
  epochs: 50
  learning_rate: 0.001
  validation_split: 0.2
  augment_swapped_pairs: false  # Not applicable for rating
  optimizer: adamw
  weight_decay: 0.01