# Best configuration for unified model (comparison task)
defaults:
  - unified_base

task_type: comparison

# Best hyperparameters found
model:
  hidden_dims:
    - 512
    - 256
    - 128
  activation: gelu
  dropout: 0.3
  batch_norm: true
  layer_norm: false
  use_user_encoding: true

training:
  epochs: 100
  learning_rate: 0.001
  validation_split: 0.2
  augment_swapped_pairs: true
  optimizer: adamw
  weight_decay: 0.01