# Configuration for comparison prediction with unified model
defaults:
  - unified_base

# Override for comparison task
task_type: comparison

# Comparison-specific settings
training:
  epochs: 50
  learning_rate: 0.001
  validation_split: 0.2
  augment_swapped_pairs: true
  optimizer: adam
  weight_decay: 0